name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Run Integration Tests
      run: cargo test --verbose --test "*"
    - name: Run Unit Tests
      run: cargo test --verbose --lib && cargo test --verbose --doc
